# Generated by Django 4.0.2 on 2022-02-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='main.Grade', to='main.Student'),
        ),
    ]
