# Generated by Django 4.0.2 on 2022-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_password_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
