# Generated by Django 4.0.2 on 2022-02-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teacher_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='score',
        ),
    ]
