# Generated by Django 4.0.2 on 2022-02-28 01:01

from django.db import migrations, models
import django.db.models.deletion
import oauth.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_grade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(default=oauth.models.expire_default)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.teacher')),
            ],
        ),
    ]
